# Generated by Django 3.2.25 on 2024-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
