# Generated by Django 3.2.25 on 2024-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvvapp', '0003_auto_20240629_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ping',
                'verbose_name_plural': 'Pings',
                'ordering': ['-created_at'],
            },
        ),
    ]
