# Generated by Django 3.2.25 on 2024-06-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvvapp', '0004_ping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='isActive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='adduser',
            old_name='isChecked',
            new_name='check',
        ),
    ]
