# Generated by Django 3.2.25 on 2024-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvvapp', '0005_auto_20240629_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
